name: mobile_school_state
description: App mobile pour lire les données dépuis le projet laravel."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.4
  share_plus: ^10.1.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
